import type {
  Home,
  PantryItem,
  ShoppingItem,
  PreparedMeal,
  DishLibraryItem,
  HomeMember,
  Profile,
} from "./types"

export const mockProfiles: Profile[] = [
  {
    id: "user-mike",
    display_name: "Mike",
    email: "mike@chefos.app",
    role: "admin",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "user-anna",
    display_name: "Anna",
    email: "anna@chefos.app",
    role: "user",
    created_at: "2024-01-05T00:00:00Z",
    updated_at: "2024-01-05T00:00:00Z",
  },
  {
    id: "user-lucia",
    display_name: "Lucia",
    email: "lucia@chefos.app",
    role: "user",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
  },
]

export const mockHomes: Home[] = [
  {
    id: "home-main",
    owner_id: "user-mike",
    name: "Main House",
    location: "Toronto, ON",
    notes: "Primary residence. Full kitchen with 6-burner range.",
    kitchen_equipment: "6-burner gas range, sous vide, combi oven, Vitamix",
    preferences: "No gluten for client. Prefer organic produce.",
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
    pantry_alert_count: 4,
    open_shopping_count: 6,
    expiring_meal_count: 3,
    member_count: 3,
  },
  {
    id: "home-cottage",
    owner_id: "user-mike",
    name: "Cottage",
    location: "Muskoka, ON",
    notes: "Weekend retreat. Smaller pantry.",
    kitchen_equipment: "4-burner electric, standard oven",
    preferences: "Casual weekend cooking, comfort food focus.",
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-06-15T00:00:00Z",
    pantry_alert_count: 5,
    open_shopping_count: 3,
    expiring_meal_count: 1,
    member_count: 1,
  },
  {
    id: "home-city",
    owner_id: "user-mike",
    name: "City Apartment",
    location: "Toronto, ON – King West",
    notes: "Pied-à-terre. Minimal pantry.",
    kitchen_equipment: "Induction cooktop, convection oven",
    preferences: "Quick weeknight meals only.",
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-06-10T00:00:00Z",
    pantry_alert_count: 2,
    open_shopping_count: 1,
    expiring_meal_count: 0,
    member_count: 1,
  },
]

export const mockHomeMembers: HomeMember[] = [
  {
    id: "member-1",
    home_id: "home-main",
    user_id: "user-mike",
    role: "admin",
    can_edit_pantry: true,
    can_add_shopping_items: true,
    can_log_meals: true,
    invited_by: "user-mike",
    created_at: "2024-01-01T00:00:00Z",
    profile: mockProfiles[0],
  },
  {
    id: "member-2",
    home_id: "home-main",
    user_id: "user-anna",
    role: "staff",
    can_edit_pantry: false,
    can_add_shopping_items: true,
    can_log_meals: false,
    invited_by: "user-mike",
    created_at: "2024-01-10T00:00:00Z",
    profile: mockProfiles[1],
  },
  {
    id: "member-3",
    home_id: "home-cottage",
    user_id: "user-lucia",
    role: "viewer",
    can_edit_pantry: false,
    can_add_shopping_items: false,
    can_log_meals: false,
    invited_by: "user-mike",
    created_at: "2024-02-05T00:00:00Z",
    profile: mockProfiles[2],
  },
]

export const mockPantryItems: PantryItem[] = [
  {
    id: "pantry-1",
    home_id: "home-main",
    created_by: "user-mike",
    name: "Organic Eggs",
    category: "Dairy & Eggs",
    quantity: 2,
    unit: "dozen",
    minimum_quantity: 2,
    preferred_brand: "Burnbrae Farms",
    storage_location: "Fridge",
    status: "Critical",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-06-18T00:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "pantry-2",
    home_id: "home-main",
    created_by: "user-mike",
    name: "Greek Yogurt",
    category: "Dairy & Eggs",
    quantity: 1,
    unit: "tub",
    minimum_quantity: 2,
    preferred_brand: "Liberté",
    storage_location: "Fridge",
    status: "Low",
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-06-17T00:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "pantry-3",
    home_id: "home-main",
    created_by: "user-mike",
    name: "Extra Virgin Olive Oil",
    category: "Oils & Condiments",
    quantity: 0,
    unit: "bottle",
    minimum_quantity: 1,
    preferred_brand: "Kirkland",
    storage_location: "Pantry",
    status: "Out of Stock",
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-06-16T00:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "pantry-4",
    home_id: "home-main",
    created_by: "user-mike",
    name: "Wild Salmon Fillet",
    category: "Proteins",
    quantity: 4,
    unit: "portions",
    minimum_quantity: 2,
    storage_location: "Freezer",
    status: "OK",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2024-06-15T00:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "pantry-5",
    home_id: "home-main",
    created_by: "user-mike",
    name: "Arborio Rice",
    category: "Grains & Pasta",
    quantity: 500,
    unit: "g",
    minimum_quantity: 250,
    storage_location: "Pantry",
    status: "OK",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "pantry-6",
    home_id: "home-cottage",
    created_by: "user-mike",
    name: "Whole Milk",
    category: "Dairy & Eggs",
    quantity: 1,
    unit: "L",
    minimum_quantity: 2,
    storage_location: "Fridge",
    status: "Low",
    created_at: "2024-05-20T00:00:00Z",
    updated_at: "2024-06-14T00:00:00Z",
    home: mockHomes[1],
  },
  {
    id: "pantry-7",
    home_id: "home-city",
    created_by: "user-mike",
    name: "Pasta",
    category: "Grains & Pasta",
    quantity: 200,
    unit: "g",
    minimum_quantity: 400,
    storage_location: "Pantry",
    status: "Critical",
    created_at: "2024-04-10T00:00:00Z",
    updated_at: "2024-06-12T00:00:00Z",
    home: mockHomes[2],
  },
]

export const mockShoppingItems: ShoppingItem[] = [
  {
    id: "shop-1",
    home_id: "home-main",
    name: "Milk",
    quantity_needed: "2L",
    category: "Dairy & Eggs",
    priority: "Normal",
    added_by: "user-anna",
    status: "Open",
    created_at: "2024-06-18T08:00:00Z",
    home: mockHomes[0],
    added_by_profile: mockProfiles[1],
  },
  {
    id: "shop-2",
    home_id: "home-main",
    name: "Salmon",
    quantity_needed: "1kg",
    category: "Proteins",
    priority: "Urgent",
    added_by: "user-mike",
    status: "Open",
    created_at: "2024-06-18T09:00:00Z",
    home: mockHomes[0],
    added_by_profile: mockProfiles[0],
  },
  {
    id: "shop-3",
    home_id: "home-main",
    name: "Extra Virgin Olive Oil",
    quantity_needed: "2 bottles",
    category: "Oils & Condiments",
    priority: "Important",
    added_by: "user-mike",
    status: "Open",
    created_at: "2024-06-17T14:00:00Z",
    home: mockHomes[0],
    added_by_profile: mockProfiles[0],
  },
  {
    id: "shop-4",
    home_id: "home-cottage",
    name: "Butter",
    quantity_needed: "500g",
    category: "Dairy & Eggs",
    priority: "Normal",
    added_by: "user-mike",
    status: "Open",
    created_at: "2024-06-16T10:00:00Z",
    home: mockHomes[1],
    added_by_profile: mockProfiles[0],
  },
]

export const mockDishLibrary: DishLibraryItem[] = [
  {
    id: "dish-1",
    created_by: "user-mike",
    name: "Chicken Soup",
    category: "Soups",
    ingredients: "Whole chicken, carrots, celery, onion, thyme, bay leaf, parsley",
    prep_time: "3 hours",
    storage_instructions: "Refrigerate up to 4 days. Freeze up to 3 months.",
    reheating_instructions: "Reheat gently on stove over medium heat.",
    tags: ["comfort", "winter", "gluten-free"],
    notes: "Client favourite. Double batch on Sundays.",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
  },
  {
    id: "dish-2",
    created_by: "user-mike",
    name: "Lemon Herb Salmon",
    category: "Fish",
    ingredients: "Salmon fillet, lemon, dill, capers, olive oil, garlic",
    prep_time: "25 min",
    storage_instructions: "Refrigerate up to 2 days.",
    reheating_instructions: "Reheat in oven at 275°F for 12 minutes.",
    tags: ["quick", "gluten-free", "light"],
    created_at: "2024-04-10T00:00:00Z",
    updated_at: "2024-06-05T00:00:00Z",
  },
  {
    id: "dish-3",
    created_by: "user-mike",
    name: "Truffle Risotto",
    category: "Pasta & Grains",
    ingredients: "Arborio rice, truffle oil, parmesan, shallots, white wine, vegetable stock",
    prep_time: "45 min",
    storage_instructions: "Refrigerate up to 3 days.",
    reheating_instructions: "Add splash of stock, reheat on medium stirring constantly.",
    tags: ["elegant", "vegetarian", "weekend"],
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-06-10T00:00:00Z",
  },
]

const today = new Date()
const addDays = (d: Date, n: number) => {
  const copy = new Date(d)
  copy.setDate(copy.getDate() + n)
  return copy.toISOString().split("T")[0]
}

export const mockMeals: PreparedMeal[] = [
  {
    id: "meal-1",
    home_id: "home-main",
    dish_id: "dish-1",
    created_by: "user-mike",
    name: "Chicken Soup",
    prepared_date: addDays(today, -3),
    expiry_date: addDays(today, 1),
    portions: 4,
    storage_location: "Main Fridge – Shelf 2",
    reheating_instructions: "Reheat on stove over medium heat.",
    status: "Use Soon",
    created_at: "2024-06-15T10:00:00Z",
    updated_at: "2024-06-15T10:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "meal-2",
    home_id: "home-main",
    dish_id: "dish-2",
    created_by: "user-mike",
    name: "Lemon Herb Salmon",
    prepared_date: addDays(today, -5),
    expiry_date: addDays(today, -1),
    portions: 2,
    storage_location: "Main Fridge – Shelf 1",
    reheating_instructions: "Oven 275°F for 12 minutes.",
    status: "Expired",
    created_at: "2024-06-13T10:00:00Z",
    updated_at: "2024-06-13T10:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "meal-3",
    home_id: "home-main",
    dish_id: "dish-3",
    created_by: "user-mike",
    name: "Truffle Risotto",
    prepared_date: addDays(today, -1),
    expiry_date: addDays(today, 4),
    portions: 3,
    storage_location: "Main Fridge – Shelf 3",
    reheating_instructions: "Add stock, stir over medium heat.",
    status: "Fresh",
    created_at: "2024-06-17T14:00:00Z",
    updated_at: "2024-06-17T14:00:00Z",
    home: mockHomes[0],
  },
  {
    id: "meal-4",
    home_id: "home-cottage",
    created_by: "user-mike",
    name: "Beef Stew",
    prepared_date: addDays(today, -7),
    expiry_date: addDays(today, -3),
    portions: 6,
    storage_location: "Cottage Fridge",
    reheating_instructions: "Reheat in pot with lid on medium-low.",
    status: "Expired",
    created_at: "2024-06-11T10:00:00Z",
    updated_at: "2024-06-11T10:00:00Z",
    home: mockHomes[1],
  },
]

// Computed helpers
export function getPantryStatus(
  quantity: number,
  minimum: number
): import("./types").PantryStatus {
  if (quantity === 0) return "Out of Stock"
  if (quantity < minimum) return "Critical"
  if (quantity <= minimum * 1.25) return "Low"
  return "OK"
}

export function getMealStatus(
  expiryDate: string
): import("./types").MealStatus {
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  const expiry = new Date(expiryDate)
  expiry.setHours(0, 0, 0, 0)
  const diffDays = Math.floor(
    (expiry.getTime() - today.getTime()) / (1000 * 60 * 60 * 24)
  )
  if (diffDays < 0) return "Expired"
  if (diffDays <= 2) return "Use Soon"
  return "Fresh"
}
